stages:
  - stage: Dev
    displayName: Dev
    jobs:
      - job: DeployADF
        displayName: Deploy ADF
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '1.1.0'
          - task: TerraformCLI@0
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              backendServiceArm: 'myARMServiceConnection'
              backendAzureRmResourceGroupName: 'myResourceGroup'
              backendAzureRmStorageAccountName: 'mystorageaccountmichel'
              backendAzureRmContainerName: 'mycontainer'
              backendAzureRmKey: 'oKPCLx06W+g8BGSGprz8xgjXroMi6odokHr9JF7b6BwSC26tFX4ctanBkNvU5g9nhuabPzKjtqkk+AStKrezHg=='
          - task: TerraformCLI@0
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              environmentServiceNameAzureRM: 'myARMServiceConnection'
